# Generated by Django 6.0.1 on 2026-03-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
