# Generated by Django 6.0.1 on 2026-03-31 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_choice_question_alter_question_quiz'),
        ('progress', '0002_alter_lectureprogress_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizattempt', to='course.quiz'),
        ),
        migrations.AlterField(
            model_name='quizattemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizattemptanswer', to='progress.quizattempt'),
        ),
    ]
