import type { Metadata } from "next";
import { BsShieldCheck } from "react-icons/bs";
import LogoWithText from "@/components/molecules/LogoWithText";




export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="auth_layout flex min-h-screen font-manrope overflow-y-hidden">
            <div className="left_side overflow-hidden relative basis-3/5 p-12  md:flex hidden flex-col items-start justify-between  bg-darkmint via-white/5 via-[1.61%] text-white">
                <div>
                    <LogoWithText Text="LMS Portal" classNameT="text-white" classNameI="backdrop-blur-[6px] bg-white/10" />
                </div>
                <div className="md:w-full xl:w-3/5">
                    <h1 className="font-extrabold  text-4xl/14 lg:text-5xl/16 text-white mb-6">Elevate your professional <span className="bg-darkbg text-darkmint/30 rounded-lg">growth</span> with data-driven insights.</h1>
                    <p className="font-normal text-lg/7 text-graylighttext mb-6">Join thousands of professionals mastering new skills through our structured, enterprise-grade learning environment.</p>
                    <div className="p-6 pt-8 flex gap-4 rounded-3xl backdrop-[5px] border border-white/10 bg-white/3 max-w-md z-30 relative">
                        <div className="basis-12 shrink-0 h-12 rounded-full bg-white/10 flex items-center justify-center"><BsShieldCheck className="w-6 h-6 text-white" /></div>
                        <div>
                            <h3 className="font-semibold text-base/6 text-white">Secure & Private</h3>
                            <p className="font-normal text-sm/5 text-graylighttext mt-2">Enterprise-grade encryption protecting your educational progress and personal data.</p>
                        </div>
                    </div>
                </div>
                <div className="font-medium text-sm/5 flex items-center gap-x-6 uppercase text-graylighttext">
                    <span>© 2026 LMS Portal</span>
                    <span>.</span>
                    <span>Privacy First</span>
                </div>

                {/* Abstract Graphic Representation */}
                <div className="absolute right-0 top-1/2 -translate-y-1/2 w-full h-full opacity-20 pointer-events-none" data-alt="Abstract geometric network connecting data points">
                    <svg fill="none" height="100%" viewBox="0 0 800 800" width="100%" xmlns="http://www.w3.org/2000/svg">
                        <path d="M100 400C100 234.315 234.315 100 400 100C565.685 100 700 234.315 700 400C700 565.685 565.685 700 400 700C234.315 700 100 565.685 100 400Z" stroke="white" strokeDasharray="10 10" strokeWidth="0.5"></path>
                        <circle cx="400" cy="400" r="200" stroke="white" strokeWidth="0.5"></circle>
                        <circle cx="250" cy="250" fill="white" r="15"></circle>
                        <circle cx="550" cy="550" fill="white" fillOpacity="0.5" r="8"></circle>
                        <line stroke="white" strokeWidth="0.5" x1="250" x2="400" y1="250" y2="400"></line>
                        <line stroke="white" strokeWidth="0.5" x1="550" x2="400" y1="550" y2="400"></line>
                    </svg>
                </div>

                <div className="absolute -botom-1/20 -right-1/20 top-[65%] left-[65%] bg-[#1A3A46] blur-[50px] rounded-full w-120 h-120"></div>
            </div>
            <div className="right_side p-6 md:p-10 lg:p-12 2xl:p-16 md:basis-2/5 w-full">
                <div className="md:hidden block">
                    <LogoWithText Text="LMS Portal" classNameT="" classNameI="bg-white" IconColor="text-darkmint" />
                </div>
                {children}
            </div>
        </main>
    );
}

