import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import QueryProvider from "@/lib/queryProvider";
import { Toaster } from "@/components/atoms/sonner";

import {Sidebar} from "@/components/organisms/SideBar";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <main className={` font-manrope antialiased bg-lightbg flex  min-h-screen`} >
                <Sidebar/>
                <main
                    className="min-h-screen flex-1 p-8  overflow-y-auto"
                >
                    {children}
                </main>
        </main>
    );
}
