# Generated by Django 6.0.1 on 2026-02-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Username',
            new_name='username',
        ),
    ]
