# Generated by Django 6.0.1 on 2026-02-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='hh', upload_to='LMS/PFP/'),
            preserve_default=False,
        ),
    ]
