# Generated by Django 6.0.1 on 2026-02-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_adminprofile_instructorprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='about',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
