# Generated by Django 5.1.2 on 2026-02-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
    ]
