# Generated by Django 6.0.1 on 2026-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_customuser_can_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='title',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
