# Generated by Django 6.0.1 on 2026-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_instructorprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
