# Generated by Django 6.0.1 on 2026-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_instructorprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='students_count',
            field=models.IntegerField(default=0),
        ),
    ]
