# Generated by Django 5.1.2 on 2026-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
