export const courses = [
    {
        ImageUrl: "/images/home/image.png",
        Name: "React Mastery",
        About: "Learn React from scratch with hands-on projects and expert guidance.",
        Price: 49,
        AvaterUrl: "",
        Instructor: "Jane Doe",
        Rate: 4.8,
        Subscribers: 1520,
        Tag: "Best Seller",
    },
    {
        ImageUrl: "/images/home/image.png",
        Name: "UI/UX Design Bootcamp",
        About: "Master UI/UX fundamentals, wireframing, and user research techniques.",
        Price: 59,
        AvaterUrl: "",
        Instructor: "John Smith",
        Rate: 4.7,
        Subscribers: 985,
        Tag: "Design",
    },
    {
        ImageUrl: "/images/home/image.png",
        Name: "Python for Data Science",
        About: "A comprehensive course covering Python basics, Pandas, and machine learning.",
        Price: 65,
        AvaterUrl: "",
        Instructor: "Emily Clark",
        Rate: 4.9,
        Subscribers: 2044,
        Tag: "Data Science",
    },
    {
        ImageUrl: "/images/home/image.png",
        Name: "Fullstack Web Development",
        About: "Build modern websites and APIs using JavaScript, Node.js, and more.",
        Price: 75,
        AvaterUrl: "",
        Instructor: "Michael Brown",
        Rate: 4.85,
        Subscribers: 1732,
        Tag: "Development",
    },
    {
        ImageUrl: "/images/home/image.png",
        Name: "Digital Marketing Essentials",
        About: "Discover SEO, email marketing, and social media strategies for growth.",
        Price: 42,
        AvaterUrl: "",
        Instructor: "Sophia Lee",
        Rate: 4.6,
        Subscribers: 1190,
        Tag: "Marketing",
    },
    {
        ImageUrl: "/images/home/image.png",
        Name: "Business Analytics Crash Course",
        About: "Unlock insights with business analytics, dashboards, and data storytelling.",
        Price: 55,
        AvaterUrl: "",
        Instructor: "David Kim",
        Rate: 4.7,
        Subscribers: 950,
        Tag: "Business",
    },
    {
        ImageUrl: "/images/home/image.png",
        Name: "Machine Learning Basics",
        About: "Get started with machine learning algorithms and model deployment.",
        Price: 69,
        AvaterUrl: "",
        Instructor: "Lisa Turner",
        Rate: 4.8,
        Subscribers: 1375,
        Tag: "Data Science",
    },
    {
        ImageUrl: "/images/home/image.png",
        Name: "Creative Graphic Design",
        About: "Learn Adobe tools and create eye-catching graphics for any purpose.",
        Price: 60,
        AvaterUrl: "",
        Instructor: "Carlos Romero",
        Rate: 4.75,
        Subscribers: 1108,
        Tag: "Design",
    },
    {
        ImageUrl: "/images/home/image.png",
        Name: "Startup Fundamentals",
        About: "Everything you need to know to launch and grow your startup.",
        Price: 58,
        AvaterUrl: "",
        Instructor: "Angela White",
        Rate: 4.6,
        Subscribers: 890,
        Tag: "Business",
    }
]
