# Generated by Django 6.0.1 on 2026-03-09 13:30
from django.utils import timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lecture_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
