# Generated by Django 6.0.1 on 2026-03-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
