# Generated by Django 6.0.1 on 2026-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
