# Generated by Django 6.0.1 on 2026-07-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='LMS/courses/thumbnail'),
            preserve_default=False,
        ),
    ]
