# Generated by Django 6.0.1 on 2026-07-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
    ]
