# Generated by Django 6.0.1 on 2026-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_lecture_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='pending'),
        ),
    ]
