# Generated by Django 6.0.1 on 2026-07-21 08:44

from django.db import migrations, models


def normalize_video_status(apps, schema_editor):
    """Fix rows written under the old lowercase default before choices were corrected."""
    Lecture = apps.get_model('course', 'Lecture')
    Lecture.objects.filter(video_status='pending').update(video_status='PENDING')


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_lecture_video_url_lecture_video_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(normalize_video_status, migrations.RunPython.noop),
    ]
