# Generated by Django 6.0.1 on 2026-08-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_lecture_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
