# Generated by Django 6.0.1 on 2026-09-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='pending_video_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
