# Generated by Django 6.0.1 on 2026-07-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_customuser_profile_picture'),
        ('course', '0013_alter_course_thumbnail'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
