import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../assets/styles/globals.css";
import QueryProvider from "@/lib/queryProvider";
import { Toaster } from "@/components/atoms/sonner";

const ManropeFont = Manrope({
    variable: "--font-manrope",
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import { authAPI } from "@/featuers/auth";
import { cookies } from "next/headers";
import { serverRefreshToken } from "@/lib/serverRefresh";


export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    // const cookieStore = await cookies()
    // const access_token = cookieStore.get('access_token')?.value
    // const refresh_token = cookieStore.get('refresh_token')?.value

    // console.log("access_token :" , access_token)
    // console.log("refresh_token :" , refresh_token)


    //     if (!access_token && refresh_token) {
    //         const refreshed = await serverRefreshToken()
    //         if (refreshed) {
    //             console.log('✅ Silent refresh successful');
    //         } else {
    //             console.log('❌ Silent refresh failed');
    //         }
    //     }

    return (
        <html lang="en">
            <body
                className={`${ManropeFont.variable} antialiased bg-lightbg font-manrope`}
            >
                <QueryProvider>
                    {children}
                </QueryProvider>
                <Toaster position="top-right"/>
            </body>
        </html>
    );
}
