import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../assets/styles/globals.css";

import NavBar from "../components/organisms/NavBar";
import Footer from "@/components/organisms/Footer";




const ManropeFont = Manrope({
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ManropeFont.variable} antialiased bg-lightbg`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
