import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../assets/styles/globals.css";



const ManropeFont = Manrope({
    variable: "--font-manrope",
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${ManropeFont.variable} antialiased bg-lightbg font-manrope`}
            >
                {children}
            </body>
        </html>
    );
}
