# Generated by Django 6.0.1 on 2026-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'refunded'), ('failed', 'failed'), ('pending', 'pending'), ('paid', 'paid')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('refunded', 'refunded'), ('failed', 'failed'), ('pending', 'pending'), ('paid', 'paid')], max_length=255),
        ),
    ]
