# Generated by Django 6.0.1 on 2026-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_alter_order_status_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'refunded'), ('failed', 'failed'), ('paid', 'paid'), ('pending', 'pending')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('refunded', 'refunded'), ('failed', 'failed'), ('paid', 'paid'), ('pending', 'pending')], max_length=255),
        ),
    ]
