# Generated by Django 6.0.1 on 2026-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_alter_order_status_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('failed', 'failed'), ('pending', 'pending'), ('refunded', 'refunded')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('failed', 'failed'), ('pending', 'pending'), ('refunded', 'refunded')], max_length=255),
        ),
    ]
