# Generated by Django 6.0.1 on 2026-07-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0011_order_created_at_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('refunded', 'refunded'), ('paid', 'paid')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('refunded', 'refunded'), ('paid', 'paid')], max_length=255),
        ),
    ]
