# Generated by Django 6.0.1 on 2026-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0014_alter_order_status_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('failed', 'failed'), ('pending', 'pending'), ('refunded', 'refunded')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('failed', 'failed'), ('pending', 'pending'), ('refunded', 'refunded')], max_length=255),
        ),
    ]
