# Generated by Django 6.0.1 on 2026-07-15 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_lecture_video_url'),
        ('enrollment', '0017_alter_order_status_alter_transaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_receipt_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method_type',
            field=models.CharField(default='card', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_receipt_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('paid', 'paid'), ('refunded', 'refunded')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('paid', 'paid'), ('refunded', 'refunded')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stripe_charge_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
