# Generated by Django 6.0.1 on 2026-07-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0018_remove_transaction_stripe_receipt_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('gateway', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Processed Webhook Event',
                'verbose_name_plural': 'Processed Webhook Events',
            },
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='stripe_charge_id',
            new_name='gateway_charge_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='stripe_payment_intent_id',
            new_name='gateway_reference',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='stripe_receipt_url',
            new_name='receipt_url',
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(default='stripe', max_length=20),
        ),
    ]
