# Generated by Django 6.0.1 on 2026-07-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0019_processedwebhookevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_gateway',
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(default='stripe', max_length=20),
        ),
    ]
